def test_untitled(self):
    driver = self.driver
    driver.get(self.base_url + "/users/53753")
    driver.find_element_by_id("realname").clear()
    driver.find_element_by_id("realname").send_keys(u"发发是去")
    driver.find_element_by_id("idnumber").clear()
    driver.find_element_by_id("idnumber").send_keys("11010519980505297x")
    driver.find_element_by_id("captcha-button").click()
    driver.find_element_by_css_selector("fieldset > input[type=\"text\"]").clear()
    driver.find_element_by_css_selector("fieldset > input[type=\"text\"]").send_keys("5642")
    driver.find_element_by_css_selector("button.confirm").click()
    driver.find_element_by_css_selector("button.confirm").click()
    driver.find_element_by_css_selector("button.confirm").click()
    driver.find_element_by_css_selector("button.confirm").click()
    driver.find_element_by_id("idcode").clear()
    driver.find_element_by_id("idcode").send_keys("550621")
    driver.find_element_by_id("idcode").clear()
    driver.find_element_by_id("idcode").send_keys("550621")
    driver.find_element_by_id("submission").click()
    driver.find_element_by_id("submission").click()
    driver.find_element_by_css_selector("span.two-step.hover").click()
